### ISSUE TITLE
Investigate issue with Elasticsearch Collector

### ISSUE THREAD

**Issue by johann8384** [OpenTSDB/tcollector#260]
```
2016-02-08 14:17:10,892 tcollector[34472] WARNING: elasticsearch.py: Traceback (most recent call last):
2016-02-08 14:17:10,892 tcollector[34472] WARNING: elasticsearch.py:   File "/Users/jcreasy/code/tcollector/collectors/0/elasticsearch.py", line 257, in <module>
2016-02-08 14:17:10,893 tcollector[34472] WARNING: elasticsearch.py:     sys.exit(main(sys.argv))
2016-02-08 14:17:10,893 tcollector[34472] WARNING: elasticsearch.py:   File "/Users/jcreasy/code/tcollector/collectors/0/elasticsearch.py", line 210, in main
2016-02-08 14:17:10,893 tcollector[34472] WARNING: elasticsearch.py:     printmetric("process.cpu.sys", d["sys_in_millis"] / 1000.)
2016-02-08 14:17:10,893 tcollector[34472] WARNING: elasticsearch.py: KeyError: 'sys_in_millis'
```

**Comment by johann8384** [comment]
Could not reproduce on current version.

**Comment by robison** [comment]
On 2.3.3, `sys_in_millis` is not a valid key returned from ES for the process key.
